version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest  # Adjust if needed for a specific version
    volumes:
      - mongo-data:/data/db  # Optional: persist data with a volume
  # Backend service
  backend:
    build: ./backend  # Assuming your backend Dockerfile is in a `backend` directory
    ports:
      - 5000:5000  # Expose backend port
    environment:
      - MONGO_URI=mongodb://mongodb:27017/liaisonpro
    depends_on:
      - mongodb     # Ensure MongoDB starts first
    volumes:
      - ./backend:/app
      - /app/node_modules
  # Frontend service
  frontend:
    build: ./frontend  # Assuming your frontend Dockerfile is in a `frontend` directory
    ports:
      - 3000:3000  # Expose frontend port
    # environment:
    #   - REACT_APP_API_URL: "http://backend:5000"
    depends_on:
      - backend    # Start backend service first
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
volumes:
  # Define volume for MongoDB data (optional)
  mongo-data:
